script:
name:Calculate symmetry
help:~
Calculate symmetry value and symmetry plane for all genotypes
(note: may take a long time for complex bodies).
Details of this method are described in http://www.framsticks.com/node/808~
code:~
function main()
{
  Simulator.print("Calculating symmetry...");

  if (GenePools[0].size == 0)
  {  
    Simulator.message("This script needs some genotypes.", 2);
    return ;
  }

  for (var pool in GenePools)
  {
    for (var g in pool)
    {
      var m = Model.newFromGeno(g.geno);
      //Simulator.message("...Calculating symmetry of "+g.name,0);
      var s = ModelSymmetry.calculateSymmetry(m); //default parameters
      Simulator.message("Symmetry of '"+g.name+"' is "+s+", plane: ["+
        ModelSymmetry.symResultA+", "+ModelSymmetry.symResultB+", "+ModelSymmetry.symResultC+"], "+ModelSymmetry.symResultD 
        ,0);
    }
  }
}

/*
fitness function that is a symmetry of a genotype for a given plane:
var m=Model.newFromGeno(this.geno);
return ModelSymmetry.calculateSymmetryForPlane(m,-0.305212, -0.939347, -0.156434, 0.0798513);
*/
~
