script:
name:Food circle
help:Arranges food pieces in a circle
code:~
function main()
{
  var food_pop=findFoodPopulation();
  if (food_pop==null)
  {
    Simulator.message("Food group not defined in your experiment.", 2);
    return ;
  }

  Simulator.print("Making food circle...");

  var siz = World.wrldsiz / 2.0;
  var full = Math.twopi;
  var step = 13.0 / (full*siz) + 0.001;
  for (var a = step;a < full;a += step)
  {
    var rgb=RGBfromHue(a*360/full);
    var hexrgb="0x%02x%02x%02x" % int(255*rgb[0]) % int(255*rgb[1]) % int(255*rgb[2]);
    var food=food_pop.add("//0\nm:Vstyle=food(color="+hexrgb+")\np:");
    var x = siz * (1.0 + Math.sin(a)) - 1.0;
    var y = siz * (1.0 + Math.cos(a)) - 1.0;
    food.locationSetBboxLow(x, y, WorldMap.getHeight(x, y));
  }
}

// in: 0..360  out: (0..1,0..1,0..1)
function RGBfromHue(hue)
{
var hh=(hue/60.0)%6.0;
var x=1.0-Math.abs(hh%2.0-1.0);
if (hh<=1) return (1,x,0);
if (hh<=2) return (x,1,0);
if (hh<=3) return (0,1,x);
if (hh<=4) return (0,x,1);
if (hh<=5) return (x,0,1);
if (hh<=6) return (1,0,x);
return (0,0,0);
}

function findFoodPopulation()
{
  for (var pop in Populations)
  {
    if (pop.name == "Food")
      return pop;
  }
  return null;
}
~
